### ISSUE TITLE
Please specify the Raspberry Pi release which this was developed/tested on

### ISSUE THREAD

**Issue by ballen4705** [Splines/raspi-captive-portal#2]
It would be very useful if your README.md file could specify which Raspberry Pi release(s) this was developed and tested on.  You could put that up front, or in the Dependencies section.

There is quite a bit of information on the net about the setup of Captive Portals on RP, but a lot of that info is out of date.  It does not apply to recent releases such as Bullseye, because the networking setup and configuration structure has changed.

I just found this in README.md: "Setup script was tested with a fresh install of Raspbian GNU/Linux 11 (bullseye) on the Raspberry Pi 4."  I suggest you put that statement up top, and also under "Dependencies".

**Comment by Splines** [comment]
Oh thanks, good to know that the setup has changed. Do you know any good resources where I can pick up the changes (just asking 'cause sometimes the official docs are not the best resources)? Feel free to fork and open a pull request so that the setup also works with newer versions (a switch would be good for backwards compatibility, e.g. keeping the config files in folder for different releases).

I've added the info to the Readme like you suggested.

**Comment by ballen4705** [comment]
You're good: most of the Captive Portal stuff I have found on the internet does NOT work with the current RP release (Bullseye).  In contrast, that is the release which you have tested on.

**Comment by Splines** [comment]
Ah, I thought you meant this setup was not working anymore with some new minor releases of debian 11 (bullseye) 🙈. But if everything works here, that's great to hear ;)
And yes, I feel you with the "most of the Captive Portal stuff I have found on the internet does NOT work with the current RP release", that's exactly why I put everything together in this repo as I had to visit so many articles to finally get this to work. It shouldn't be that difficult.

**Comment by ballen4705** [comment]
I just did a test with the latest and greatest RP bullseye 64-bit lite release.  The install failed because the following packages have unmet dependencies:

libnode72 conflicts with nodejs-legacy
nodejs conflicts with npm
The final failure message is "E: unable to correct problems, you have held broken packages"

This is on a clean, out of the box bullseye system, freshly updated, and with nothing done to it other than configure the network.

**Comment by ballen4705** [comment]
Will do.  Is there an actual log file that I can send?  Or do you mean the console output?

**Comment by Splines** [comment]
You could just copy the console output. If it is too long, you can also pipe it to a file and afterwards copy the contents of the file to the new issue.

```
command 1> /random/path/to/stdout.txt 2> /random/path/to/stderr.txt
```
