### ISSUE TITLE
How to change splines.portal to our own portal name

### ISSUE THREAD

**Issue by FredBesterwitch** [Splines/raspi-captive-portal#7]
G'day, Thanks on developing such a excellent project, I got the whole system running.
Can you please tell me how to change "splines.portal" to our own portal name, it tried changing the host name to "our.portal" in server.ts, but page did not load.
Also the header on the Browser "Sign in to ...", we are customising this page display some info. can we change "Sign in to" to something else?

Thanks

**Comment by Splines** [comment]
Hey there, glad you got the captive portal up and running.

With regards to the hostname. This is indeed the only place where I specify it:

https://github.com/Splines/raspi-captive-portal/blob/b3d84f66bab0b39159bcde05b723160e66eefe4e/server/src/server.ts#L8

So changing it there should work. Have you rebuilt the project via `cd server/` followed by `npm run build`? And have you restarted the service afterwards via

```sh
sudo systemctl restart access-point-server
```


Concerning the "Sign in to..." text: this is probably coming from the bare-bone browser provided by your OS just to log in into a captive portal. I don't know if there's a way to customize it and probably think the answer is "no". However, you can still just open any "real" browser and access the web page to not have this text. But of course, that's one additional step users have to take and indeed that's a bit annoying. But if you build something more complex, you'll have to indicate to your users they should browse the site with a "real" browser anyways as the bare-bone captive-portal-browser will probably not support all the niceties of HTML and JS.

**Comment by Splines** [comment]
I hope this solved your issue, if not feel free to open it again.
